name: qadam
description: Personal growth and self-development app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  google_fonts: ^6.3.2
  lottie: any
  firebase_core: any
  firebase_auth: ^6.1.2
  firebase_database: any
  cloud_firestore: ^6.1.0
  firebase_storage: any
  provider: any
  rive: any
  simple_animations: ^5.2.0
  intl: ^0.20.2
  fl_chart: ^1.1.1
  lucide_icons: ^0.257.0
  flutter_staggered_animations: ^1.1.1
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/rive/
    - assets/animations/
